/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmlpoo;

import java.util.ArrayList;
import logica.WriteXMLFile;

/**
 *
 * @author peperony
 */
public class Paises extends javax.swing.JFrame {
    private ArrayList<String> provincias;
    private ArrayList<String> paisesLimitrofes;
    private WriteXMLFile archivo;
    /**
     * Creates new form Paises
     */
    public Paises() {
        archivo = new WriteXMLFile();
        provincias = new ArrayList<>();
        paisesLimitrofes = new ArrayList<>();
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTamanio = new javax.swing.JLabel();
        jTextFieldTamanio = new javax.swing.JTextField();
        jLabePoblacion = new javax.swing.JLabel();
        jTextFieldPoblacion = new javax.swing.JTextField();
        jLabelIdioma = new javax.swing.JLabel();
        jTextFieldIdioma = new javax.swing.JTextField();
        jLabelProvincia = new javax.swing.JLabel();
        jTextFieldProvincia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProvincia = new javax.swing.JTextArea();
        jButtonPrivincia = new javax.swing.JButton();
        jLabelPaisesLimitrofes = new javax.swing.JLabel();
        jTextFieldPaisesLimitrofes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPaisesLimitrofes = new javax.swing.JTextArea();
        jButtonPaisesLimitrofes = new javax.swing.JButton();
        jButtonAgregarPais = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 230, 40));

        jLabelTamanio.setText("Tamaño territorial");
        getContentPane().add(jLabelTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(jTextFieldTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 230, 40));

        jLabePoblacion.setText("Población");
        getContentPane().add(jLabePoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(jTextFieldPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 230, 40));

        jLabelIdioma.setText("Idioma");
        getContentPane().add(jLabelIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(jTextFieldIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 230, 40));

        jLabelProvincia.setText("Provincia");
        getContentPane().add(jLabelProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));
        getContentPane().add(jTextFieldProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 230, 40));

        jTextAreaProvincia.setColumns(20);
        jTextAreaProvincia.setRows(5);
        jTextAreaProvincia.setAutoscrolls(false);
        jTextAreaProvincia.setFocusable(false);
        jScrollPane1.setViewportView(jTextAreaProvincia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 230, 200));

        jButtonPrivincia.setText("Agregar");
        jButtonPrivincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrivinciaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrivincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 40));

        jLabelPaisesLimitrofes.setText("Países limitrofes");
        getContentPane().add(jLabelPaisesLimitrofes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));
        getContentPane().add(jTextFieldPaisesLimitrofes, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 240, 40));

        jTextAreaPaisesLimitrofes.setColumns(20);
        jTextAreaPaisesLimitrofes.setRows(5);
        jTextAreaPaisesLimitrofes.setFocusable(false);
        jScrollPane2.setViewportView(jTextAreaPaisesLimitrofes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 240, 210));

        jButtonPaisesLimitrofes.setText("Agregar");
        jButtonPaisesLimitrofes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaisesLimitrofesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPaisesLimitrofes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 110, 40));

        jButtonAgregarPais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAgregarPais.setText("Agregar país");
        jButtonAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 230, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Guardar Documento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 230, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrivinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrivinciaActionPerformed
        String provincia = jTextFieldProvincia.getText();
        if (!provincia.equals("")){
            provincias.add(provincia);
            provincia = jTextAreaProvincia.getText() + provincia + "\n";
            jTextAreaProvincia.setText(provincia);
            jTextFieldProvincia.setText("");
        }
    }//GEN-LAST:event_jButtonPrivinciaActionPerformed

    private void jButtonPaisesLimitrofesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaisesLimitrofesActionPerformed
        String paisesLimitrofes = jTextFieldPaisesLimitrofes.getText();
        if (!paisesLimitrofes.equals("")){
            paisesLimitrofes = jTextAreaPaisesLimitrofes.getText() + paisesLimitrofes + "\n";
            jTextAreaPaisesLimitrofes.setText(paisesLimitrofes);
            jTextFieldPaisesLimitrofes.setText("");
        }
    }//GEN-LAST:event_jButtonPaisesLimitrofesActionPerformed

    private void jButtonAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPaisActionPerformed
        if (validarInfo()) {
            archivo.agregarPaiz();
            archivo.agregarCaracteristica("Nombre", jTextFieldNombre.getText());
            archivo.agregarCaracteristica("Tamaño", jTextFieldTamanio.getText());
            archivo.agregarCaracteristica("Población", jTextFieldPoblacion.getText());
            archivo.agregarCaracteristica("Idioma", jTextFieldIdioma.getText());
            for (int i = 0; i < provincias.size(); i++) {
                archivo.agregarCaracteristica("Provincia", provincias.get(i));
            }
            for (int i = 0; i < paisesLimitrofes.size(); i++) {
                archivo.agregarCaracteristica("Frontera", paisesLimitrofes.get(i));
            }
            javax.swing.JOptionPane.showMessageDialog(null, "País agregado");
            jTextFieldNombre.setText("");
            jTextFieldTamanio.setText("");
            jTextFieldPoblacion.setText("");
            jTextFieldIdioma.setText("");
            jTextAreaPaisesLimitrofes.setText("");
            jTextAreaProvincia.setText("");
            paisesLimitrofes.clear();
            provincias.clear();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Error con los datos ingresados");
        }
    }//GEN-LAST:event_jButtonAgregarPaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (archivo.escribirDocumento()){
            javax.swing.JOptionPane.showMessageDialog(null, "Se guardo el archovo correctamente");
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Ocurrio un error en el archivo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean isNum(String num){
	try {
		Integer.parseInt(num);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    private boolean validarInfo() {
        if (jTextFieldNombre.getText().equals("")){
            return false;
        } else if (!isNum(jTextFieldPoblacion.getText())){
            return false;
        } else if (!isNum(jTextFieldTamanio.getText())){
            return false;
        } else if (jTextFieldIdioma.getText().equals("")) {
            return false;
        } else if (jTextAreaProvincia.getText().equals("")) {
            return false;
        } else if (jTextAreaPaisesLimitrofes.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paises().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregarPais;
    private javax.swing.JButton jButtonPaisesLimitrofes;
    private javax.swing.JButton jButtonPrivincia;
    private javax.swing.JLabel jLabePoblacion;
    private javax.swing.JLabel jLabelIdioma;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPaisesLimitrofes;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPaisesLimitrofes;
    private javax.swing.JTextArea jTextAreaProvincia;
    private javax.swing.JTextField jTextFieldIdioma;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPaisesLimitrofes;
    private javax.swing.JTextField jTextFieldPoblacion;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldTamanio;
    // End of variables declaration//GEN-END:variables
}
